{{- if gt (len .Values.secrets) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deploy.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "deploy.labels" . | nindent 5 }}
type: Opaque
data: 
{{- range .Values.secrets }}
    {{- if .valueIsFile }}
    {{ .name }}: {{ $.Files.Get .value | b64enc }}
    {{- else }}
    {{ .name }}: {{ .value | b64enc }}
    {{- end }}
{{- end }}
{{ end }}